name: CI

on:
  push:
    branches: [main, prod]
  pull_request:
    branches: [main, prod]

jobs:
  build:
    name: Lint and Typecheck
    env:
      SKIP_ENV_VALIDATION: 1

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [20.x, 22.x]
        os: [ubuntu-latest]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - name: Cache pnpm store
        uses: actions/cache@v4.0.2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - uses: pnpm/action-setup@v4.0.0
        with:
          version: 8

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4.0.2
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"

      - name: Install deps
        run: pnpm install

      - name: Cache Next.js build
        uses: actions/cache@v4.0.2
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-

      - name: Lint
        run: pnpm lint

      - name: Typecheck
        run: pnpm typecheck
